language: go
sudo: false

go:
  - 1.6

install:
  - export VERSION="${VERSION:-latest}"
  - make

script:
  - make test
  - make VERSION="$VERSION" dist

deploy:
  provider: releases
  api_key: $GITHUB_ACCESS_TOKEN
  overwrite: true
  file_glob: true
  file:
    - gotpl-alpine-linux-amd64-*.tar.gz
    - gotpl-linux-amd64-*.tar.gz
    - gotpl-linux-i386-*.tar.gz
    - gotpl-linux-armel-*.tar.gz
    - gotpl-linux-armhf-*.tar.gz
    - gotpl-darwin-amd64-*.tar.gz
    - gotpl-darwin-i386-*.tar.gz
  skip_cleanup: true
  on:
    branch: master
    tags: true

notifications:
  email:
    on_success: never
    on_error: never
