language: go
sudo: false

go:
  - 1.6

install: make

script: make test

after_success:
  - make dist
  - provider: releases
    api_key:
      secure: $GITHUB_ACCESS_TOKEN
    file:
      - dist/alpine-linux/amd64/gotpl
      - dist/linux/amd64/gotpl
      - dist/linux/i386/gotp
      - dist/linux/armel/gotpl
      - dist/linux/armhf/gotpl
      - dist/darwin/amd64/gotpl
      - dist/darwin/i386/gotpl
    skip_cleanup: true
    on:
      repo: wodby/gotpl
      tags: true
      all_branches: true

notifications:
  email:
    on_success: never
    on_error: never
