language: go

go:
  - 1.6

install: make

script: make test

after_success:
  - make dist
  - provider: releases
    api_key:
      secure: $GITHUB_ACCESS_TOKEN
    file: ./dist/*/*/gotpl
    file_glob: true
    skip_cleanup: true
    on:
      repo: wodby/gotpl
      tags: true
      all_branches: true

notifications:
  email:
    on_success: never
