name: Build

on:
  push:
    branches:
    - master

    tags:
    - '*'

  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux,darwin]
        arch: [amd64,arm64]
    container:
      image: golang:alpine
    env:
      GOOS: ${{ matrix.os }}
      GOARCH: ${{ matrix.arch }}
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: apk add --update make gcc bash
    - name: build
      run: make
    - name: test
      run: make test
    - name: prepare artifact
      if: startsWith(github.ref, 'refs/tags/')
      run: make package
    - name: Get the version
      if: startsWith(github.ref, 'refs/tags/')
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - uses: xresloader/upload-to-github-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: gotpl-*.tar.gz
        overwrite: true
        tags: true
        draft: false
        tag_name: ${{ steps.get_version.outputs.VERSION }}
